// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufqzmkagmjyboxwbklcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcXpta2FnbWp5Ym94d2JrbGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTc2MjQsImV4cCI6MjA3MTM3MzYyNH0.rpEZsCkeP_FGAOnR3FTjuvh2_FPG-adtLfh8d0IcsWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});